name: Build Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2020-01-13
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Get Submodules
        run: 'git submodule update --init --recursive'
      - name: Install Dependencies
        run: |
          apt update
          apt install autoconf autogen libtool systemd -y
      - name: Build
        run: |
          ./autogen.sh && ./configure CFLAGS='-g -O2' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 --prefix=/usr
          make -j`nproc --all`