name: Build Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: px4io/px4-dev-base-bionic:2020-01-13
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Get Submodules
        run: 'git submodule update --init --recursive'
      - name: Install Dependencies
        run: |
          apt update
          apt install autoconf autogen libtool systemd -y
      - name: Build
        run: |
          ./autogen.sh && ./configure CFLAGS='-g -O2' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 --prefix=/usr
          make -j`nproc --all`
      - name: Run Mainloop Unit Tests
        run: |
          make mainloop_test
          ./mainloop_test

  alpine-linux:
    name: alpine 3.11.6 (musl)
    runs-on: ubuntu-18.04
    container: alpine:3.11.6
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: install tools
        run: apk update && apk add autoconf automake build-base git libtool linux-headers openssl-dev perl-extutils-pkgconfig python3 && pip3 install future
      - name: configure
        run: ./autogen.sh && ./configure CFLAGS='-g -O2' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib --disable-systemd --prefix=/usr
      - name: build
        run: make
